config/routes.rb
Rails.application.routes.draw do
  root 'parkings#index'

  resources :parkings

  devise_for :users

end

app/models/parking.rb
class Parking < ActiveRecord::Base
  belongs_to :user

  validates :name, presence: true
  validates :process_step, presence: true

  ROLES_PROCESS = {
    commercial: [
      "Appel client",
      "Prise de RDV",
      "Récupération des critères du parking",
      "Envoi du contrat",
      "Réception du contrat"
    ],
    operation: [
      "Création de la fiche parking dans le backoffice",
      "Call d’activation"
    ],
    marketing: ["Lancement campagne Adwords"]
  }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :parkings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_filter :update_sanitized_params, if: :devise_controller?

  protected

  # To permit role attribute (user registration)
  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:email, :name, :password, :password_confirmation, :role)}
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
  before_action :set_parking, only: [:show, :edit, :update]
    
  def index
    @parkings = Parking.all
  end

  def new
    @user = current_user
    @parking = Parking.new
  end

  def show
  end

  def create
    @user = User.find(current_user.id)
    @parking = @user.parkings.new(parking_params)

    if @parking.save
      redirect_to parkings_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update

    if @parking.update(parking_params)
      redirect_to @parking
    else
      render @parking
    end
  end

  private

  def set_parking
    @parking = Parking.find(params[:id])
  end

  def parking_params
    params.require(:parking).permit(:name, :process_step)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  private

  def users_params
    params.require(:user).permit(:name, :email, :password, :role)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parkings_helper.rb
module ParkingsHelper
  def available_step_process role
    Parking::ROLES_PROCESS[role.to_sym]
  end
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ParkApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <% flash.each do |key, message| %>
        <div><%= message %></div>
    <% end %>

    <% unless user_signed_in? %>
    <div class="navbar-right">
        <ul class="nav navbar-nav">
            <li>
                <%= link_to "Sign up", new_user_registration_path %>
            </li>
            <li>
                <%= link_to "Sign in", new_user_session_path %>
            </li>
        </ul>
    </div>
    <% end %>    

    <% if user_signed_in? %>
    <div class="navbar-right">
        <p class="navbar-text">
          Signed in as <%= current_user.email %>
        </p>
        <ul class="nav navbar-nav">
            <li>
                <%= link_to "Sign out", destroy_user_session_path,
            method: :delete %>
            </li>
        </ul>
    </div>
    <div class="page-header">
        <h1><%= link_to "Parkings", parkings_path %></h1>
        <ul class="actions">
            <li><%= link_to "New Parking", new_parking_path,
              class: "btn btn-success" %></li>
        </ul>
    </div>
    <% end %>

    <%= yield %>

  </div>
</body>
</html>

app/views/parkings/edit.html.erb
<%= simple_form_for @parking do |p| %> 
  <div>
    <%= p.input :name, label: "Nom du parking" %>
  </div>

  <div>
    <%= p.input :process_step, collection:available_step_process(current_user.role), label: "Etape du process", include_blank: false %>
  </div>

  <%= p.submit "Update", class: "btn btn-primary" %>
<% end %>

app/views/parkings/index.html.erb
<table class="table table-bordered">
  <tr>  
    <td>
      Nom
    </td>
    <td>
      Etape du process
    </td>
    <td>
      Créateur
    </td>
    <td>
      Crée le
    </td>
    <td>
      Mis à jour
    </td>
    <td>
      Actions
    </td>
  </tr>

  <% @parkings.each do |p| %>
    <tr>
      <td>
        <%= p.name %>
      </td>
      <td>  
        <%= p.process_step %>
      </td>
      <td>
        <%= p.user.name %>
      </td>
      <td>
        <%= p.created_at.strftime("%m/%d/%Y") %>
      </td>
      <td>
        <%= p.updated_at.strftime("%m/%d/%Y") %>
      </td>
      <td>
        <%= link_to "Editer", edit_parking_path(p), class: "btn btn-primary" %>
      </td>
    </tr>
  <% end %> 
</table>

app/views/parkings/new.html.erb
<%= simple_form_for @parking do |p| %> 
  <div>
    <%= p.input :name, label:"Nom du parking" %>
  </div>

  <div class="form-group">
    <label>Créateur</label>
    <input type="text" name="createur" value="<%= current_user.name %>" class="form-control" disabled>
  </div>

  <div>
    <%= p.input  :process_step, collection:available_step_process(current_user.role), label:"Etape du process", include_blank: false %>
  </div>

  <%= p.submit "Create", class: "btn btn-primary" %>
<% end %>

app/views/parkings/show.html.erb
<%= @parking.name %> Nom
<br>
<%= @parking.user_id %> user id
<br>
<%= @parking.process_step %> process

<%= link_to "Editer", edit_parking_path(@parking), class: "btn btn-primary" %>